//! Python generated-output analyzer.

use std::path::{Path, PathBuf};

use sweeploom_core::{Blocker, ProcessSnapshot, RebuildCost};

use crate::git::{GitSafety, blocker_for, inspect};
use crate::size::dir_size;

/// One Python cleanup offer.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PythonOffer {
    /// Project root.
    pub project: PathBuf,
    /// Path that would be deleted.
    pub path: PathBuf,
    /// Short label for UI/CLI.
    pub label: &'static str,
    /// Logical bytes.
    pub logical_bytes: u64,
    /// False when a cap or read error made this a lower bound.
    pub size_complete: bool,
    /// Rebuild cost.
    pub rebuild: RebuildCost,
    /// True when auto-select is forbidden.
    pub blocked: bool,
    /// Why it is blocked, if it is.
    pub blocker: Option<Blocker>,
    /// Pre-select when SAFE generated bytecode/cache.
    pub preselect: bool,
}

/// Discover Python generated-output offers for one project.
#[must_use]
pub fn python_offers(project: &Path, processes: &[ProcessSnapshot]) -> Vec<PythonOffer> {
    python_offers_with(project, processes, &inspect)
}

/// [`python_offers`] with a shared Git reader. Git is read only when an offer exists.
pub(crate) fn python_offers_with(
    project: &Path,
    processes: &[ProcessSnapshot],
    git: &dyn Fn(&Path) -> GitSafety,
) -> Vec<PythonOffer> {
    if !is_python_project(project) {
        return Vec::new();
    }
    let mut offers = Vec::new();
    for cache in ["__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"] {
        push_offer(&mut offers, project, cache, RebuildCost::Low, true);
    }
    for env in [".venv", "venv"] {
        push_offer(&mut offers, project, env, RebuildCost::High, false);
    }
    if !offers.is_empty() {
        let tools = ["python", "python3", "pip", "poetry", "uv", "pytest"];
        let blocker = blocker_for(project, processes, &tools, git);
        for offer in &mut offers {
            offer.blocked = blocker.is_some();
            offer.blocker = blocker;
            offer.preselect &= blocker.is_none();
        }
    }
    offers
}

fn is_python_project(project: &Path) -> bool {
    ["pyproject.toml", "requirements.txt", "setup.py", "Pipfile"]
        .iter()
        .any(|marker| project.join(marker).is_file())
}

fn push_offer(
    offers: &mut Vec<PythonOffer>,
    project: &Path,
    name: &'static str,
    rebuild: RebuildCost,
    preselect: bool,
) {
    let path = project.join(name);
    if !path.is_dir() {
        return;
    }
    let size = dir_size(&path);
    let logical_bytes = size.bytes;
    if logical_bytes == 0 {
        return;
    }
    offers.push(PythonOffer {
        project: project.to_path_buf(),
        path,
        label: name,
        logical_bytes,
        size_complete: size.complete,
        rebuild,
        blocked: false,
        blocker: None,
        preselect,
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn missing_markers_yield_nothing() {
        assert!(python_offers(Path::new("/no-such-sweeploom-py"), &[]).is_empty());
    }

    #[test]
    fn discovers_pycache_not_empty_venv() {
        let root = std::env::temp_dir().join(format!("sweeploom-py-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("__pycache__")).unwrap();
        fs::create_dir_all(root.join(".venv")).unwrap();
        fs::write(root.join("pyproject.toml"), "[project]\nname=\"demo\"\n").unwrap();
        fs::write(root.join("__pycache__").join("a.pyc"), vec![0_u8; 256]).unwrap();
        fs::write(root.join(".venv").join("pyvenv.cfg"), b"home = /\n").unwrap();
        let offers = python_offers(&root, &[]);
        assert!(offers.iter().any(|item| item.label == "__pycache__"));
        assert!(offers.iter().any(|item| item.label == ".venv"));
        let cache = offers
            .iter()
            .find(|item| item.label == "__pycache__")
            .unwrap();
        assert!(cache.preselect);
        let venv = offers.iter().find(|item| item.label == ".venv").unwrap();
        assert!(!venv.preselect);
        let _ = fs::remove_dir_all(&root);
    }
}
