//! Python generated-output analyzer.

use std::path::{Path, PathBuf};

use sweeploom_core::{Blocker, ProcessSnapshot, RebuildCost};

use crate::git::{GitSafety, inspect};
use crate::size::dir_logical_bytes;

/// One Python cleanup offer.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PythonOffer {
    /// Project root.
    pub project: PathBuf,
    /// Path that would be deleted.
    pub path: PathBuf,
    /// Short label for UI/CLI.
    pub label: &'static str,
    /// Logical bytes.
    pub logical_bytes: u64,
    /// Rebuild cost.
    pub rebuild: RebuildCost,
    /// True when auto-select is forbidden.
    pub blocked: bool,
    /// Why it is blocked, if it is.
    pub blocker: Option<Blocker>,
    /// Pre-select when SAFE generated bytecode/cache.
    pub preselect: bool,
}

/// Discover Python generated-output offers for one project.
#[must_use]
pub fn python_offers(project: &Path, processes: &[ProcessSnapshot]) -> Vec<PythonOffer> {
    if !is_python_project(project) {
        return Vec::new();
    }
    let blocker = python_blocker(project, processes);
    let blocked = blocker.is_some();
    let mut offers = Vec::new();
    push_offer(
        &mut offers,
        project,
        "__pycache__",
        RebuildCost::Low,
        true,
        blocked,
        blocker.clone(),
    );
    for cache in [".pytest_cache", ".mypy_cache", ".ruff_cache"] {
        push_offer(
            &mut offers,
            project,
            cache,
            RebuildCost::Low,
            true,
            blocked,
            blocker.clone(),
        );
    }
    for env in [".venv", "venv"] {
        push_offer(
            &mut offers,
            project,
            env,
            RebuildCost::High,
            false,
            blocked,
            blocker.clone(),
        );
    }
    offers
}

fn is_python_project(project: &Path) -> bool {
    ["pyproject.toml", "requirements.txt", "setup.py", "Pipfile"]
        .iter()
        .any(|marker| project.join(marker).is_file())
}

fn python_blocker(project: &Path, processes: &[ProcessSnapshot]) -> Option<Blocker> {
    if processes
        .iter()
        .any(|process| process_blocks(process, project))
    {
        return Some(Blocker::ActiveProcess);
    }
    let git = inspect(project);
    if matches!(git, GitSafety::Unknown) {
        return Some(Blocker::UnknownGitState);
    }
    git.assessment().blockers.first().cloned()
}

fn process_blocks(process: &ProcessSnapshot, project: &Path) -> bool {
    let Some(cwd) = &process.cwd else {
        return false;
    };
    if !cwd.starts_with(project) {
        return false;
    }
    let name = process.name.to_ascii_lowercase();
    ["python", "python3", "pip", "poetry", "uv", "pytest"]
        .iter()
        .any(|needle| name.contains(needle))
}

fn push_offer(
    offers: &mut Vec<PythonOffer>,
    project: &Path,
    name: &'static str,
    rebuild: RebuildCost,
    preselect: bool,
    blocked: bool,
    blocker: Option<Blocker>,
) {
    let path = project.join(name);
    if !path.is_dir() {
        return;
    }
    let logical_bytes = dir_logical_bytes(&path);
    if logical_bytes == 0 {
        return;
    }
    offers.push(PythonOffer {
        project: project.to_path_buf(),
        path,
        label: name,
        logical_bytes,
        rebuild,
        blocked,
        blocker,
        preselect: preselect && !blocked,
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn missing_markers_yield_nothing() {
        assert!(python_offers(Path::new("/no-such-sweeploom-py"), &[]).is_empty());
    }

    #[test]
    fn discovers_pycache_not_empty_venv() {
        let root = std::env::temp_dir().join(format!("sweeploom-py-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("__pycache__")).unwrap();
        fs::create_dir_all(root.join(".venv")).unwrap();
        fs::write(root.join("pyproject.toml"), "[project]\nname=\"demo\"\n").unwrap();
        fs::write(root.join("__pycache__").join("a.pyc"), vec![0_u8; 256]).unwrap();
        fs::write(root.join(".venv").join("pyvenv.cfg"), b"home = /\n").unwrap();
        let offers = python_offers(&root, &[]);
        assert!(offers.iter().any(|item| item.label == "__pycache__"));
        assert!(offers.iter().any(|item| item.label == ".venv"));
        let cache = offers
            .iter()
            .find(|item| item.label == "__pycache__")
            .unwrap();
        assert!(cache.preselect);
        let venv = offers.iter().find(|item| item.label == ".venv").unwrap();
        assert!(!venv.preselect);
        let _ = fs::remove_dir_all(&root);
    }
}
